Jkeenan/gha 258 win32 20200901
atoomic/perl pull request #259
Opened 2020-09-01 19:24 UTC by jkeenan

This p.r. is untested; I have no Windows.  It *may* clean up some `use strict 'vars';` failures.

2020-09-01 20:30 UTC, toddr requested changes
Given a branch, I can switch to windows and try this out.

2020-09-01 20:30 UTC, toddr commented on cpan/Win32API-File/t/file.t
> +#use Win32;
I don't follow how this can function with these off.

2020-09-01 20:30 UTC, toddr commented on cpan/Win32API-File/t/file.t
> +#use Win32API::File qw(:ALL);
Accidentally commented?

2020-09-01 20:45 UTC, jkeenan commented on cpan/Win32API-File/t/file.t
> +#use Win32API::File qw(:ALL);
Corrected.

2020-09-03 19:05 UTC, toddr approved these changes

2020-09-03 19:07 UTC, toddr commented
I think we're good to go.

2020-09-03 19:33 UTC, closed without merging

2020-09-03 19:35 UTC, jkeenan commented
Rebased on target branch, merged into target branch, which was just now pushed upstream as commit da0a32ff74ba2ef2686dc14c210eb832fbff472c.